# Functions to copy resource easily
function(copy_res file)
  cmake_parse_arguments(COPY_SHADER "" "DESTINATION FROM" "" ${ARGN})
endfunction(copy_res)

function(copy_shader shader)
  cmake_parse_arguments(COPY_SHADER "" "DESTINATION" "" ${ARGN})
  if(NOT COPY_SHADER_DESTINATION)
    file(COPY "${curr_dir}/res/shader/${shader}.vert.glsl" DESTINATION "${target_dir}/shader/")
    file(COPY "${curr_dir}/res/shader/${shader}.frag.glsl" DESTINATION "${target_dir}/shader/")
  else()
    file(COPY "${curr_dir}/res/shader/${shader}.vert.glsl" DESTINATION "${target_dir}/shader/${COPY_SHADER_DESTINATION}/")
    file(COPY "${curr_dir}/res/shader/${shader}.frag.glsl" DESTINATION "${target_dir}/shader/${COPY_SHADER_DESTINATION}/")
  endif()
endfunction(copy_shader)

function(copy_model model)
  cmake_parse_arguments(COPY_MODEL "" "DESTINATION" "" ${ARGN})
  if(NOT COPY_MODEL_DESTINATION)
    file(COPY "${curr_dir}/res/model/${model}" DESTINATION "${target_dir}/model/")
  else()
    file(COPY "${curr_dir}/res/model/${model}" DESTINATION "${target_dir}/image/${COPY_MODEL_DESTINATION}/")
  endif()
endfunction(copy_model)

function(copy_image image)
  cmake_parse_arguments(COPY_IMAGE "" "DESTINATION" "" ${ARGN})
  if(NOT COPY_IMAGE_DESTINATION)
    file(COPY "${curr_dir}/res/image/${image}" DESTINATION "${target_dir}/image/")
  else()
    file(COPY "${curr_dir}/res/image/${image}" DESTINATION "${target_dir}/image/${COPY_IMAGE_DESTINATION}/")
  endif()
endfunction(copy_image)